version: "3"

services:
  php-cockpit-react-static:
    image: wodby/php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    build: ./build/
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog-cockpit-react-static:1025
      COLUMNS: 80 # Set 80 columns for docker exec -it.
    volumes:
#      - ./:/var/www/html
## For macOS users (https://wodby.com/stacks/drupal/docs/local/docker-for-mac/)
      - ../www:/var/www/html:cached # User-guided caching
#      - cockpit-react-static-sync:/var/www/html # Docker-sync
## For Xdebug profiler files
#      - files:/mnt/files

  nginx-cockpit-react-static:
    image: wodby/nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php-cockpit-react-static
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php-cockpit-react-static
      NGINX_SERVER_ROOT: /var/www/html
      NGINX_VHOST_PRESET: $NGINX_VHOST_PRESET
    volumes:
#      - ./:/var/www/html
# For macOS users (https://wodby.com/stacks/drupal/docs/local/docker-for-mac/)
      - ../www:/var/www/html:cached # User-guided caching
#      - cockpit-react-static-sync:/var/www/html # Docker-sync
    ports:
      - '8088:80'

  mailhog-cockpit-react-static:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"
    ports:
      - '8025:8025'

#volumes:
## Docker-sync for macOS users
#  cockpit-react-static-sync:
#    external: true
## For Xdebug profiler
#  files:
